package com.springapp.model.enums;

/**
 * Created by Mathieu on 6/21/2016.
 */
public enum EventType {
    SUBSCRIPTION_ORDER, SUBSCRIPTION_CHANGE, SUBSCRIPTION_CANCEL, SUBSCRIPTION_NOTICE, USER_ASSIGNMENT, USER_UNASSIGNMENT, USER_UPDATED
}
